### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by matrix4767** [Whiax/sd-webui-nulie#1]
I get this when i click the enhance button.

Traceback (most recent call last):
  File "G:\stable-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\stable-webui\venv\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\stable-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\stable-webui\venv\lib\site-packages\gradio\utils.py", line 410, in async_iteration
    return next(iterator)
  File "G:\stable-webui\extensions\sd-webui-nulienhance\scripts\nul_image_enhancer.py", line 50, in enhance_image
    with safe_open(pth, framework="pt", device="cpu") as f:
FileNotFoundError: The system cannot find the path specified. (os error 3)

**Comment by Whiax** [comment]
Hi, thanks for the report. Oh right I get it, I changed the name of the repo, sorry about that. It should be fixed now!
